# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.6
  jobs:
    build:
      docker:
        - image: circleci/node:10.0.0
          steps:
            - checkout
        - run:
            command: mvn -e clean verify -Dnet.bytebuddy.experimental=true
            name: Build the project
        - coveralls/upload

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.0
    steps:
      - checkout
      - run: 'mvn -e clean verify -Dnet.bytebuddy.experimental=true'
